-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."softcartDimDate"
(
    dateid integer NOT NULL,
    date date,
    "Year" integer,
    "Quarter" integer,
    "QuarterName" character varying(2),
    "Month" integer,
    "Monthname" text,
    "Day" integer,
    "Weekday" integer,
    "WeekdayName" text,
    PRIMARY KEY (dateid)
);

CREATE TABLE public."softcartDimCategory"
(
    categoryid integer NOT NULL,
    category text,
    PRIMARY KEY (categoryid)
);

CREATE TABLE public."softcartDimItem"
(
    itemid integer NOT NULL,
    itemname text,
    categoryid integer,
    PRIMARY KEY (itemid)
);

CREATE TABLE public."softcartDimCountry"
(
    countryid integer NOT NULL,
    country text,
    PRIMARY KEY (countryid)
);

CREATE TABLE public."softcartFactSales"
(
    orderid integer NOT NULL,
    dateid integer,
    itemid integer,
    countryid integer,
    categoryid integer,
    amount numeric(50, 2),
    PRIMARY KEY (orderid)
);

ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (dateid)
    REFERENCES public."softcartDimDate" (dateid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (itemid)
    REFERENCES public."softcartDimItem" (itemid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (countryid)
    REFERENCES public."softcartDimCountry" (countryid)
    NOT VALID;


ALTER TABLE public."softcartDimItem"
    ADD FOREIGN KEY (categoryid)
    REFERENCES public."softcartDimCategory" (categoryid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (categoryid)
    REFERENCES public."softcartDimCategory" (categoryid)
    NOT VALID;

END;